// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwh597SU92nMBZNb_06Q_IlrtwNU4N1ys',
    appId: '1:136701382239:web:50b9d3cf31b971efa955ea',
    messagingSenderId: '136701382239',
    projectId: 'project-tasbih-3021f',
    authDomain: 'project-tasbih-3021f.firebaseapp.com',
    storageBucket: 'project-tasbih-3021f.appspot.com',
    measurementId: 'G-9K82W48VLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7LxbSFUQbgietoHRHOJBkmuLOdrgWuI4',
    appId: '1:136701382239:android:5d4c2c16116d0cf7a955ea',
    messagingSenderId: '136701382239',
    projectId: 'project-tasbih-3021f',
    storageBucket: 'project-tasbih-3021f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8VpHW4oT-vQN9IYkfzV7uxs-zsQ0qNTA',
    appId: '1:136701382239:ios:2392eb8bf0f3fdc9a955ea',
    messagingSenderId: '136701382239',
    projectId: 'project-tasbih-3021f',
    storageBucket: 'project-tasbih-3021f.appspot.com',
    iosClientId: '136701382239-7p3fidkl7ij3gbn040v54f6oanhvbo9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasbix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8VpHW4oT-vQN9IYkfzV7uxs-zsQ0qNTA',
    appId: '1:136701382239:ios:2392eb8bf0f3fdc9a955ea',
    messagingSenderId: '136701382239',
    projectId: 'project-tasbih-3021f',
    storageBucket: 'project-tasbih-3021f.appspot.com',
    iosClientId: '136701382239-7p3fidkl7ij3gbn040v54f6oanhvbo9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasbix',
  );
}
